name: Avisar Itens Adicionados

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

jobs:
  notify-added:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install web-push
      - run: node send-added-notification.js
        env:
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
